[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_HELIUS_API_KEY = "your-helius-api-key"
  REACT_APP_CLAUDE_API_KEY = "your-claude-api-key" 